services:
- docker
git:
  submodules: false
env:
  global:
    - REGISTRY_USER='robot$vikoverflow-robot'

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - cp deployment/Dockerfile.backend backend
  - cp deployment/Dockerfile.frontend frontend
  - cp deployment/vikoverflow.template frontend
  - docker build -t vikoverflow-backend-deploy -f backend/Dockerfile.backend backend
  - docker build -t vikoverflow-frontend-deploy -f frontend/Dockerfile.frontend frontend

before_deploy:
  - docker login https://registry.k8s.sch.bme.hu -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script:
    docker tag vikoverflow-backend-deploy registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-backend:$TRAVIS_TAG &&
    docker tag vikoverflow-backend-deploy registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-backend:latest &&
    docker push registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-backend:$TRAVIS_TAG &&
    docker push registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-backend:latest &&
    docker tag vikoverflow-frontend-deploy registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-frontend:$TRAVIS_TAG &&
    docker tag vikoverflow-frontend-deploy registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-frontend:latest &&
    docker push registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-frontend:$TRAVIS_TAG &&
    docker push registry.k8s.sch.bme.hu/vikoverflow/vikoverflow-frontend:latest
  on:
    tags: true

after_deploy:
  - "curl -d '{\"version\":\"$'TRAVIS_TAG'\", \"token\":\"'$FRONTEND_TOKEN'\"}' -H \"Content-Type: application/json\" -X POST devteam-updater.dev.k8s.sch.bme.hu"
  - "curl -d '{\"version\":\"'$TRAVIS_TAG'\", \"token\":\"'$BACKEND_TOKEN'\"}' -H \"Content-Type: application/json\" -X POST devteam-updater.dev.k8s.sch.bme.hu"