version: "3"

services:
  db:
    image: postgres:alpine
    volumes:
      - vikoverflow-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - SERVER_URL=http://proxy:5000

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:5000
    depends_on:
      - backend
      - frontend

volumes:
  vikoverflow-data:
    external: true
