version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - vikoverflow-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
      - ./frontend/package.json:/code/package.json
    ports:
      - 3000:3000
  
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  vikoverflow-data:
    external: true
