apiVersion: v1
kind: Service
metadata:
  name: vikoverflow-backend
  namespace: devteam-kszk-bme-hu
  labels:
    app: vikoverflow
    component: backend
spec:
  ports:
  - name: vikoverflow-backend
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: vikoverflow
    component: backend
  type: ClusterIP