apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikoverflow-db
  namespace: devteam-kszk-bme-hu
  labels:
    app: vikoverflow
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikoverflow
      component: database
  template:
    metadata:
      labels:
        app: vikoverflow
        component: database
    spec:
      containers:
      - name: vikoverflow-database
        image: postgres:11-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vikoverflow-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vikoverflow-db-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: vikoverflow-db-credentials
              key: db
        volumeMounts:
        - name: vikoverflow-db-mount
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: vikoverflow-db-mount
          persistentVolumeClaim:
            claimName: vikoverflow-db-claim
