apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikoverflow-frontend
  namespace: devteam-kszk-bme-hu
  labels:
    app: vikoverflow
    component: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vikoverflow
      component: frontend
  template:
    metadata:
      labels:
        app: vikoverflow
        component: frontend
    spec:
      containers:
      - name: vikoverflow-frontend
        image: devteamsch/vikoverflow-frontend:0.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: http://vikoverflow-backend:8000
